import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { apiFetch } from '../lib/api';

interface SummaryItem {
    id: string;
    youtube_url: string;
    video_id: string;
    video_title: string;
    thumbnail_url: string;
    summary_text: string;
    created_at: string;
    user_name?: string;
    user_email?: string;
}

interface Props {
    showAll?: boolean;
}

export default function SummaryHistory({ showAll = false }: Props) {
    const { user } = useAuth();
    const [summaries, setSummaries] = useState<SummaryItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [deleteLoading, setDeleteLoading] = useState<string | null>(null);

    const isAdmin = user?.role === 'admin';
    const fetchAll = showAll && isAdmin;

    useEffect(() => {
        loadSummaries();
    }, [fetchAll]);

    const loadSummaries = async () => {
        setLoading(true);
        try {
            const url = fetchAll ? '/ai/summaries?all=true' : '/ai/summaries';
            const data = await apiFetch<{ summaries: SummaryItem[] }>(url);
            setSummaries(data.summaries);
        } catch (err) {
            console.error('Failed to load summaries:', err);
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async (id: string) => {
        if (!confirm('Delete this summary?')) return;
        setDeleteLoading(id);
        try {
            await apiFetch(`/ai/summaries/${id}`, { method: 'DELETE' });
            setSummaries((prev) => prev.filter((s) => s.id !== id));
        } catch (err) {
            console.error('Delete failed:', err);
        } finally {
            setDeleteLoading(null);
        }
    };

    const filtered = summaries.filter((s) =>
        s.video_title?.toLowerCase().includes(search.toLowerCase())
    );

    return (
        <div className="space-y-8">
            <div>
                <h1 className="text-3xl font-bold text-dark-100">
                    {fetchAll ? (
                        <>All <span className="gradient-text">Summaries</span></>
                    ) : (
                        <>My <span className="gradient-text">Summaries</span></>
                    )}
                </h1>
                <p className="text-dark-400 mt-2">
                    {fetchAll
                        ? 'View all summaries generated by users on this platform.'
                        : 'Browse your previously generated study notes.'}
                </p>
            </div>

            {/* Search */}
            <div className="relative max-w-md">
                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4 absolute left-4 top-1/2 -translate-y-1/2 text-dark-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8" /><line x1="21" y1="21" x2="16.65" y2="16.65" /></svg>
                <input
                    type="text"
                    placeholder="Search by video title..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="w-full pl-11 pr-4 py-3 rounded-xl input-dark text-dark-100 placeholder-dark-500 text-sm"
                />
            </div>

            {/* Content */}
            {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {[1, 2, 3].map((i) => (
                        <div key={i} className="glass-card p-4 space-y-3 animate-pulse">
                            <div className="w-full h-36 bg-dark-700 rounded-lg" />
                            <div className="h-4 bg-dark-700 rounded w-3/4" />
                            <div className="h-3 bg-dark-700 rounded w-1/2" />
                        </div>
                    ))}
                </div>
            ) : filtered.length === 0 ? (
                <div className="glass-card p-12 text-center">
                    <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-dark-700/50 flex items-center justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8 text-dark-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /></svg>
                    </div>
                    <p className="text-dark-400 font-medium">
                        {search ? 'No matching summaries found' : 'No summaries yet'}
                    </p>
                    {!search && (
                        <Link to="/summarizer" className="text-primary-400 hover:text-primary-300 text-sm mt-2 inline-block">
                            Generate your first summary →
                        </Link>
                    )}
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                    {filtered.map((s) => (
                        <div key={s.id} className="glass-card overflow-hidden hover:scale-[1.02] transition-transform duration-200 group">
                            <div className="relative">
                                <img
                                    src={s.thumbnail_url}
                                    alt={s.video_title}
                                    className="w-full h-40 object-cover"
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-dark-900/80 to-transparent" />
                                <a
                                    href={s.youtube_url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="absolute top-3 right-3 p-2 rounded-lg bg-dark-800/80 text-dark-300 hover:text-white transition-colors opacity-0 group-hover:opacity-100"
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" /><polyline points="15 3 21 3 21 9" /><line x1="10" y1="14" x2="21" y2="3" /></svg>
                                </a>
                            </div>
                            <div className="p-4">
                                <h3 className="text-sm font-semibold text-dark-100 line-clamp-2 mb-1">
                                    {s.video_title || 'Untitled Video'}
                                </h3>
                                {fetchAll && s.user_name && (
                                    <p className="text-xs text-primary-400 mb-1">by {s.user_name}</p>
                                )}
                                <p className="text-xs text-dark-500 mb-3">
                                    {new Date(s.created_at).toLocaleDateString('en-US', {
                                        month: 'short', day: 'numeric', year: 'numeric',
                                    })}
                                </p>
                                <div className="flex gap-2">
                                    <Link
                                        to={`/summaries/${s.id}`}
                                        className="flex-1 text-center px-3 py-2 rounded-lg text-xs font-medium bg-primary-600/15 text-primary-400 hover:bg-primary-600/25 transition-colors"
                                    >
                                        View Notes
                                    </Link>
                                    <button
                                        onClick={() => handleDelete(s.id)}
                                        disabled={deleteLoading === s.id}
                                        className="px-3 py-2 rounded-lg text-xs font-medium bg-dark-700/50 text-dark-400 hover:bg-red-500/15 hover:text-red-400 transition-colors disabled:opacity-50"
                                    >
                                        {deleteLoading === s.id ? '...' : 'Delete'}
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
