import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { apiFetch } from '../lib/api';

interface Summary {
    id: string;
    youtube_url: string;
    video_id: string;
    video_title: string;
    thumbnail_url: string;
    summary_text: string;
    created_at: string;
    user_name?: string;
    user_email?: string;
}

export default function SummaryDetail() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [summary, setSummary] = useState<Summary | null>(null);
    const [loading, setLoading] = useState(true);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        loadSummary();
    }, [id]);

    const loadSummary = async () => {
        try {
            const data = await apiFetch<{ summary: Summary }>(`/ai/summaries/${id}`);
            setSummary(data.summary);
        } catch {
            navigate('/summaries');
        } finally {
            setLoading(false);
        }
    };

    const handleCopy = async () => {
        if (summary) {
            await navigator.clipboard.writeText(summary.summary_text);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    const handleDownload = () => {
        if (!summary) return;
        const blob = new Blob([`# ${summary.video_title}\n\n${summary.summary_text}`], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${summary.video_title?.replace(/[^a-z0-9]/gi, '_') || 'summary'}.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleDelete = async () => {
        if (!confirm('Delete this summary?')) return;
        try {
            await apiFetch(`/ai/summaries/${id}`, { method: 'DELETE' });
            navigate('/summaries');
        } catch (err) {
            console.error('Delete failed:', err);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="w-10 h-10 border-4 border-primary-500 border-t-transparent rounded-full animate-spin" />
            </div>
        );
    }

    if (!summary) return null;

    return (
        <div className="space-y-6 animate-fade-in">
            {/* Back button */}
            <Link to="/summaries" className="inline-flex items-center gap-2 text-dark-400 hover:text-dark-200 transition-colors text-sm">
                <svg xmlns="http://www.w3.org/2000/svg" className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="19" y1="12" x2="5" y2="12" /><polyline points="12 19 5 12 12 5" /></svg>
                Back to Summaries
            </Link>

            {/* Video header */}
            <div className="glass-card p-6 flex flex-col md:flex-row items-start gap-5">
                <img
                    src={summary.thumbnail_url}
                    alt={summary.video_title}
                    className="w-full md:w-56 h-36 object-cover rounded-xl"
                />
                <div className="flex-1">
                    <h1 className="text-xl font-bold text-dark-100">{summary.video_title}</h1>
                    {summary.user_name && (
                        <p className="text-sm text-primary-400 mt-1">Generated by {summary.user_name}</p>
                    )}
                    <p className="text-dark-500 text-sm mt-2">
                        {new Date(summary.created_at).toLocaleDateString('en-US', {
                            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
                        })}
                    </p>
                    <div className="flex flex-wrap gap-2 mt-4">
                        <a
                            href={summary.youtube_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-4 py-2 rounded-lg text-xs font-medium bg-red-500/15 text-red-400 hover:bg-red-500/25 transition-colors inline-flex items-center gap-1.5"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19.1c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z" /><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02" /></svg>
                            Watch Video
                        </a>
                        <button
                            onClick={handleCopy}
                            className="px-4 py-2 rounded-lg text-xs font-medium bg-dark-700/50 text-dark-300 hover:bg-dark-600 transition-colors inline-flex items-center gap-1.5"
                        >
                            {copied ? '✓ Copied!' : 'Copy Notes'}
                        </button>
                        <button
                            onClick={handleDownload}
                            className="px-4 py-2 rounded-lg text-xs font-medium bg-dark-700/50 text-dark-300 hover:bg-dark-600 transition-colors inline-flex items-center gap-1.5"
                        >
                            Download .md
                        </button>
                        <button
                            onClick={handleDelete}
                            className="px-4 py-2 rounded-lg text-xs font-medium bg-red-500/10 text-red-400 hover:bg-red-500/20 transition-colors inline-flex items-center gap-1.5"
                        >
                            Delete
                        </button>
                    </div>
                </div>
            </div>

            {/* Summary content */}
            <div className="glass-card p-8">
                <div
                    className="prose prose-invert prose-sm max-w-none
            prose-headings:text-dark-100 prose-headings:font-semibold
            prose-h2:text-lg prose-h2:mt-6 prose-h2:mb-3 prose-h2:border-b prose-h2:border-dark-700/50 prose-h2:pb-2
            prose-p:text-dark-300 prose-p:leading-relaxed
            prose-li:text-dark-300
            prose-strong:text-dark-100
            prose-table:text-dark-300
            prose-th:text-dark-200 prose-th:border-dark-600
            prose-td:border-dark-700
            prose-a:text-primary-400 prose-a:no-underline hover:prose-a:text-primary-300
            prose-blockquote:border-primary-500 prose-blockquote:text-dark-400"
                    dangerouslySetInnerHTML={{ __html: renderMarkdown(summary.summary_text) }}
                />
            </div>
        </div>
    );
}

function renderMarkdown(md: string): string {
    let html = md
        .replace(/^### (.+)$/gm, '<h3>$1</h3>')
        .replace(/^## (.+)$/gm, '<h2>$1</h2>')
        .replace(/^# (.+)$/gm, '<h1>$1</h1>')
        .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.+?)\*/g, '<em>$1</em>')
        .replace(/^- (.+)$/gm, '<li>$1</li>')
        .replace(/^(\d+)\. (.+)$/gm, '<li>$2</li>')
        .replace(/^---$/gm, '<hr/>')
        .replace(/\n\n/g, '</p><p>')
        .replace(/\n/g, '<br/>');

    html = html.replace(/(<li>.*?<\/li>)(\s*<br\/>)*(<li>)/g, '$1$3');
    html = html.replace(/(?<!<\/ul>|<\/ol>)(<li>)/g, '<ul>$1');
    html = html.replace(/(<\/li>)(?![\s\S]*?<li>)/g, '$1</ul>');

    html = html.replace(/\|(.+)\|/g, (match) => {
        const cells = match.split('|').filter(Boolean).map((c) => c.trim());
        if (cells.every((c) => /^[-:]+$/.test(c))) return '';
        return '<tr>' + cells.map((c) => `<td>${c}</td>`).join('') + '</tr>';
    });
    html = html.replace(/(<tr>.*?<\/tr>)/gs, '<table>$1</table>');

    return `<div>${html}</div>`;
}
